<?php
/**
 * lang settings.
 */
switch ($lang) {
     case "nl_NL":
            $lnews = 'Nieuws';
            $labout = 'Over ons';
            $lalbums = 'Albums';
            $lalbumst = 'Foto albums';
            $levents = 'Evenementen';
            $ladress = 'Adres';
            $lyoutube = 'Youtube';
            $lcall = 'Bel nu!';
            $likes = 'likes en';
            $ltalk = 'praten er al over';
            $lroute = 'Route';
            $lshare = 'Delen op Twitter';
            $lsharegoogle = 'Delen op Google+';
			$lcomment = 'Geef commentaar of vind dit leuk';
			$lseecomment = 'Zie het commentaar';
            $lmore = 'Meer weergeven';
            $lles = 'MINDER';
            $lfacebookvid = 'Video\'s';
            $prefix = '';
            $lby = 'door';
            $lsecond = ' seconden geleden';
            $lminut = ' minuut geleden';
            $lminuts = ' minuten geleden';
            $lhour = ' uur geleden';
            $lhours = ' uur geleden';
            $lday = ' dag geleden';
            $ldays = ' dagen geleden';
            $lweek = ' week geleden';
            $lweeks = ' weken geleden';
         break;
     case "en_EN":
            $lnews = 'News';
            $labout = 'About us';
            $lalbums = 'Albums';
            $lalbumst = 'Photo albums';
            $levents = 'Events';
            $ladress = 'Adress';
            $lyoutube = 'Youtube';
            $lcall = 'Call now!';
            $likes = 'likes and';
            $ltalk = 'talking about it';
            $lroute = 'Route';
            $lshare = 'Share on Twitter';
            $lsharegoogle = 'Share on Google+';
			$lcomment = 'Comment or like !';
			$lseecomment = 'Show comments';
            $lmore = 'See More';
            $lles = 'LESS';
            $lfacebookvid = 'Video\'s';
            $prefix = '';
            $lby = 'by';
            $lsecond = ' seconds ago';
            $lminut = ' minute ago';
            $lminuts = ' minutes ago';
            $lhour = ' hour ago';
            $lhours = ' hours ago';
            $lday = ' day ago';
            $ldays = ' days ago';
            $lweek = ' week ago';
            $lweeks = ' weeks ago';
         break;
     case "de_DE":
            $lnews = 'Nachrichten';
            $labout = '&Uuml;ber uns';
            $lalbums = 'Alben';
            $lalbumst = 'Foto-Alben';
            $levents = 'Geschehen';
            $ladress = 'Adresse';
            $lyoutube = 'Youtube';
            $lcall = 'Rufen Sie jetzt an!';
            $likes = 'mag und';
            $ltalk = 'dar&uuml;ber zu reden';
            $lroute = 'Route';
            $lshare = 'Share on Twitter';
            $lsharegoogle = 'Share on Google+';
			$lcomment = 'Kommentar !';
			$lseecomment = 'Kommentare anzeigen';
            $lmore = 'MEHR LESEN';
            $lles = 'WENIGER';
            $lfacebookvid = 'Video\'s';
            $prefix = 'vor ';
            $lby = 'von';
            $lsecond = ' sekunden';
            $lminut = ' minute';
            $lminuts = ' minuten';
            $lhour = ' stunden';
            $lhours = ' stunden';
            $lday = ' tag';
            $ldays = ' tage';
            $lweek = ' woche';
            $lweeks = ' wochen';
         break;
     case "fr_FR":
            //http://www.degraeve.com/reference/specialcharacters.php for specialchars
            $lnews = 'Nouvelles';
            $labout = 'A propos';
            $lalbums = 'Albums';
            $lalbumst = 'Albums photos';
            $levents = '&Eacute;v&eacute;nements';
            $ladress = 'Adresse';
            $lyoutube = 'Youtube';
            $lcall = 'Appelez d&egrave;s maintenant!';
            $likes = 'Aime et';
            $ltalk = 'Parler';
            $lroute = 'Route';
            $lshare = 'Partager sur Twitter';
            $lsharegoogle = 'Partager sur Google+';
			$lcomment = 'Commentaire !';
			$lseecomment = 'Afficher les commentaires';
            $lmore = 'LIRE LA SUITE';
            $lles = 'MOINS';
            $lfacebookvid = 'Vid&eacute;os';
            $prefix = 'il y a ';
            $lby = 'par';
            $lsecond = ' secondes';
            $lminut = ' minute';
            $lminuts = ' minutes';
            $lhour = ' heure';
            $lhours = ' heures';
            $lday = ' jour';
            $ldays = ' jours';
            $lweek = ' semaine';
            $lweeks = ' semaines';
         break;
    default:
            $lnews = 'News';
            $labout = 'About us';
            $lalbums = 'Albums';
            $lalbumst = 'Photo albums';
            $levents = 'Events';
            $ladress = 'Adress';
            $lyoutube = 'Youtube';
            $lcall = 'Call now!';
            $likes = 'likes and';
            $ltalk = 'talking about it';
            $lroute = 'Route';
            $lshare = 'Share on Twitter';
            $lsharegoogle = 'Share on Google+';
			$lcomment = 'Comment or like !';
			$lseecomment = 'Show comments';
            $lmore = 'See More';
            $lles = 'LESS';
            $lfacebookvid = 'Video\'s';
            $prefix = '';
            $lby = 'by';
            $lsecond = ' seconds ago';
            $lminut = ' minute ago';
            $lminuts = ' minutes ago';
            $lhour = ' hour ago';
            $lhours = ' hours ago';
            $lday = ' day ago';
            $ldays = ' days ago';
            $lweek = ' week ago';
            $lweeks = ' weeks ago';
 }
?>
